### ISSUE TITLE
No vlan tag and source pci in interface hostdev mode

### ISSUE THREAD

**Issue by s3rj1k** [libvirt/libvirt-go-xml#20]
Example xml below:
```
    <interface type='hostdev' managed='yes'>
      <mac address='52:54:01:9a:a9:17'/>
      <driver name='vfio'/>
      <source>
        <address type='pci' domain='0x0000' bus='0x06' slot='0x10' function='0x0'/>
      </source>
      <vlan>
        <tag id='101'/>
      </vlan>
      <model type='rtl8139'/>
      <alias name='hostdev0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </interface>
```

**Comment by berrange** [comment]
This should be covered by the following two commits


commit 2caa464c96b4794af0ff871c4e710d7cd034a486
Author: Daniel P. Berrange <berrange@redhat.com>
Date:   Mon Nov 27 13:44:27 2017 +0000

    Add support for remaining interface config options
    
    Signed-off-by: Daniel P. Berrange <berrange@redhat.com>

commit 5d75f25903792fdc2578071325a46b615965466f
Author: Daniel P. Berrange <berrange@redhat.com>
Date:   Mon Nov 27 11:02:53 2017 +0000

    Refactor interface source to use a union approach
    
    Signed-off-by: Daniel P. Berrange <berrange@redhat.com>


There should in fact be nearly 100% coverage of libvirt domani XML now. It can roundtrip all sample QEMU XML files in the libvirt test suite now.
