### ISSUE TITLE
Something in the last 24h broke the builds

### ISSUE THREAD

**Issue by purpleidea** [libvirt/libvirt-go-xml#21]
Our commits started failing:

eg: https://travis-ci.org/purpleidea/mgmt/jobs/308710004#L811

This happened within less than 24h... So something seems to have changed here to break API or compatibility.

**Comment by jonathangold** [comment]
@purpleidea appears to be caused by this commit: https://github.com/libvirt/libvirt-go-xml/commit/6d974488983874541c4df61ee5f0b306544ceb28

**Comment by jonathangold** [comment]
@purpleidea, Looks like the we need to change [this loop in virt.go](https://github.com/purpleidea/mgmt/blob/cf2325a2daa1ba6df1f4095ed450e733eb110bd7/resources/virt.go#L186).
Instead of checking the value of `x.Target.Type == "virtio"`, we need to check if `x.Target.VirtIO != nil`

**Comment by purpleidea** [comment]
@jonathangold WFM-- Thanks

@berrange Any background on the API break? Want to write the patch :)

**Comment by jonathangold** [comment]
@purpleidea, might need to change [this line too](https://github.com/purpleidea/mgmt/blob/cf2325a2daa1ba6df1f4095ed450e733eb110bd7/resources/virt.go#L957)

**Comment by berrange** [comment]
The API had to change to support new domain XML content. There's no general promise of API stability for the structs, as when new XML content is defined by libvirt it may require changes to the structs. So you shouldn't expect to be able to blindly rebase to git master without risk of API change.
