### ISSUE TITLE
(Un)marshal <hookData> ?

### ISSUE THREAD

**Issue by s3rj1k** [libvirt/libvirt-go-xml#22]
Add support for hookData defined for network hook [wiki](https://www.libvirt.org/hooks.html)

`<hookData>
  <network>
     <name>$network_name</name>
     <uuid>afca425a-2c3a-420c-b2fb-dd7b4950d722</uuid>
     ...
  </network>
  <domain type='$domain_type' id='$domain_id'>
     <name>$domain_name</name>
     <uuid>afca425a-2c3a-420c-b2fb-dd7b4950d722</uuid>
     ...
  </domain>
</hookData>`

**Comment by berrange** [comment]
Yes, we could support this - i forgot about this special format.
