### ISSUE TITLE
*uint in type DomainAddress struct

### ISSUE THREAD

**Issue by pacepi** [libvirt/libvirt-go-xml#9]
@chemhack @vincentbernat @purpleidea 

Hi, 
In domain.go,
type DomainAddress struct {
	Type       string `xml:"type,attr"`
	Controller *uint  `xml:"controller,attr"`
	Bus        *uint  `xml:"bus,attr"`
	Port       *uint  `xml:"port,attr"`
}

Can I use "uint" instead of  "*uint" ?

**Comment by berrange** [comment]
These fields need to be optional and 0 is a potentially valid value so we can't use omitempty
